/**
 * Gambling Website Blocklist Generator for Cloudflare Workers
 * Searches for gambling websites and generates AdGuard-compatible blocklists
 */

// Configuration
const CONFIG = {
  // Search keywords for gambling websites (Indonesian and English)
  SEARCH_KEYWORDS: [
    'judi online', 'slot online', 'casino online', 'poker online',
    'togel online', 'betting online', 'situs judi', 'bandar judi',
    'gambling site', 'online casino', 'slot machine', 'poker room',
    'sports betting', 'lottery online', 'bingo online', 'blackjack online',
    'roulette online', 'baccarat online', 'craps online', 'video poker'
  ],
  
  // Gambling-related keywords for validation
  VALIDATION_KEYWORDS: [
    'deposit', 'withdraw', 'jackpot', 'bonus', 'promo',
    'win', 'bet', 'gamble', 'casino', 'poker', 'slot',
    'togel', 'lottery', 'jackpot', 'real money', 'cash',
    'login', 'register', 'member', 'agen', 'bandar'
  ],
  
  // Common gambling TLDs and patterns
  GAMBLING_TLDS: [
    '.casino', '.bet', '.gambling', '.poker', '.slot',
    '.vegas', '.jackpot', '.betting', '.lottery', '.bingo'
  ],
  
  // AdGuard blocklist format
  BLOCKLIST_HEADER: `! Title: Gambling Websites Blocklist
! Description: Auto-generated gambling website blocklist for AdGuard
! Homepage: https://github.com/KancellKe2/gambling-blocklist
! Last modified: ${new Date().toISOString()}
! License: MIT
!
! Block gambling websites
! Generated by Gambling Blocklist Worker
!
`,
  
  // Search engines to use (with API keys if available)
  SEARCH_ENGINES: {
    google: {
      url: 'https://www.googleapis.com/customsearch/v1',
      params: {
        key: 'YOUR_GOOGLE_API_KEY',
        cx: 'YOUR_CUSTOM_SEARCH_ENGINE_ID',
        num: 10
      }
    },
    bing: {
      url: 'https://api.bing.microsoft.com/v7.0/search',
      params: {
        count: 10,
        mkt: 'id-ID'
      }
    }
  }
};

// Main worker class
export default {
  async scheduled(event, env, ctx) {
    console.log('Starting scheduled gambling site scan...');
    await this.scanAndGenerateBlocklist(env);
  },

  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    
    // Handle different routes
    if (url.pathname === '/scan') {
      // Trigger manual scan
      await this.scanAndGenerateBlocklist(env);
      return new Response('Scan completed', { status: 200 });
    }
    
    if (url.pathname === '/blocklist') {
      // Return current blocklist
      const blocklist = await env.BLOCKLIST_KV.get('current-blocklist');
      return new Response(blocklist || 'No blocklist available', {
        headers: { 'Content-Type': 'text/plain' }
      });
    }
    
    if (url.pathname === '/status') {
      // Return status information
      const stats = await env.BLOCKLIST_KV.get('stats', { type: 'json' });
      return new Response(JSON.stringify(stats || {}, null, 2), {
        headers: { 'Content-Type': 'application/json' }
      });
    }
    
    return new Response('Gambling Blocklist Worker', {
      headers: { 'Content-Type': 'text/plain' }
    });
  },

  async scanAndGenerateBlocklist(env) {
    const discoveredSites = new Set();
    const validatedSites = new Set();
    
    console.log('Starting site discovery...');
    
    // Method 1: Search engine queries
    for (const keyword of CONFIG.SEARCH_KEYWORDS) {
      try {
        const sites = await this.searchForGamblingSites(keyword);
        sites.forEach(site => discoveredSites.add(site));
        console.log(`Found ${sites.length} sites for keyword: ${keyword}`);
      } catch (error) {
        console.error(`Error searching for "${keyword}":`, error);
      }
    }
    
    // Method 2: Common gambling domain patterns
    const commonPatterns = this.getCommonGamblingPatterns();
    commonPatterns.forEach(pattern => discoveredSites.add(pattern));
    
    console.log(`Total discovered sites: ${discoveredSites.size}`);
    
    // Validate discovered sites
    console.log('Starting site validation...');
    for (const site of discoveredSites) {
      try {
        const isValid = await this.validateGamblingSite(site);
        if (isValid) {
          validatedSites.add(site);
          console.log(`Validated gambling site: ${site}`);
        }
      } catch (error) {
        console.error(`Error validating ${site}:`, error);
      }
    }
    
    console.log(`Total validated gambling sites: ${validatedSites.size}`);
    
    // Generate blocklist
    const blocklist = this.generateBlocklist(validatedSites);
    
    // Store results
    await env.BLOCKLIST_KV.put('current-blocklist', blocklist);
    await env.BLOCKLIST_KV.put('stats', JSON.stringify({
      lastScan: new Date().toISOString(),
      totalDiscovered: discoveredSites.size,
      totalValidated: validatedSites.size,
      sites: Array.from(validatedSites)
    }));
    
    console.log('Blocklist generation completed');
    return blocklist;
  },

  async searchForGamblingSites(keyword) {
    const sites = [];
    
    // Try Google Custom Search if API key is available
    if (CONFIG.SEARCH_ENGINES.google.params.key !== 'YOUR_GOOGLE_API_KEY') {
      try {
        const googleResults = await this.searchGoogle(keyword);
        sites.push(...googleResults);
      } catch (error) {
        console.error('Google search failed:', error);
      }
    }
    
    // Try Bing if API key is available
    if (CONFIG.SEARCH_ENGINES.bing.params.appKey) {
      try {
        const bingResults = await this.searchBing(keyword);
        sites.push(...bingResults);
      } catch (error) {
        console.error('Bing search failed:', error);
      }
    }
    
    // Fallback: Generate probable gambling domains based on keyword
    const probableDomains = this.generateProbableDomains(keyword);
    sites.push(...probableDomains);
    
    return [...new Set(sites)];
  },

  async searchGoogle(keyword) {
    const params = new URLSearchParams({
      ...CONFIG.SEARCH_ENGINES.google.params,
      q: keyword
    });
    
    const response = await fetch(`${CONFIG.SEARCH_ENGINES.google.url}?${params}`);
    const data = await response.json();
    
    return data.items?.map(item => this.extractDomain(item.link)) || [];
  },

  async searchBing(keyword) {
    const params = new URLSearchParams({
      ...CONFIG.SEARCH_ENGINES.bing.params,
      q: keyword
    });
    
    const response = await fetch(`${CONFIG.SEARCH_ENGINES.bing.url}?${params}`, {
      headers: {
        'Ocp-Apim-Subscription-Key': CONFIG.SEARCH_ENGINES.bing.params.appKey
      }
    });
    
    const data = await response.json();
    return data.webPages?.value?.map(page => this.extractDomain(page.url)) || [];
  },

  generateProbableDomains(keyword) {
    const domains = [];
    const baseWords = keyword.split(' ');
    
    // Common domain patterns for gambling sites
    const patterns = [
      'situs{word}',
      '{word}online',
      'agen{word}',
      'bandar{word}',
      '{word}terpercaya',
      '{word}resmi',
      'judi{word}',
      '{word}gratis',
      '{word}slot',
      '{word}casino'
    ];
    
    for (const baseWord of baseWords) {
      for (const pattern of patterns) {
        const domain = pattern.replace('{word}', baseWord);
        domains.push(`${domain}.com`);
        domains.push(`${domain}.net`);
        domains.push(`${domain}.org`);
        domains.push(`${domain}.id`);
        domains.push(`${domain}.co`);
      }
    }
    
    return domains;
  },

  getCommonGamblingPatterns() {
    // Generate common gambling domain patterns
    const patterns = [];
    const gamblingWords = ['casino', 'poker', 'slot', 'bet', 'gambling', 'togel', 'judi'];
    const tlds = ['com', 'net', 'org', 'id', 'co', 'xyz', 'site', 'online', 'club'];
    
    for (const word of gamblingWords) {
      for (const tld of tlds) {
        patterns.push(`${word}.${tld}`);
        patterns.push(`${word}online.${tld}`);
        patterns.push(`online${word}.${tld}`);
        patterns.push(`${word}terpercaya.${tld}`);
      }
    }
    
    return patterns;
  },

  extractDomain(url) {
    try {
      const urlObj = new URL(url);
      return urlObj.hostname.replace(/^www\./, '');
    } catch {
      return null;
    }
  },

  async validateGamblingSite(domain) {
    try {
      // Method 1: Check domain patterns
      if (this.isGamblingDomain(domain)) {
        return true;
      }
      
      // Method 2: Check page content
      const response = await fetch(`https://${domain}`, {
        headers: {
          'User-Agent': 'Mozilla/5.0 (compatible; GamblingBlocklist/1.0)',
          'Accept': 'text/html'
        },
        redirect: 'follow',
        cf: { ttl: 300 }
      });
      
      if (!response.ok) return false;
      
      const html = await response.text();
      const content = html.toLowerCase();
      
      // Check for gambling keywords
      let keywordCount = 0;
      for (const keyword of CONFIG.VALIDATION_KEYWORDS) {
        if (content.includes(keyword)) {
          keywordCount++;
        }
      }
      
      // If enough keywords found, consider it gambling
      if (keywordCount >= 3) {
        return true;
      }
      
      // Method 3: Check for gambling-related meta tags
      const gamblingMetaPatterns = [
        /og:.*gambling/i,
        /og:.*casino/i,
        /og:.*betting/i,
        /og:.*slot/i,
        /description.*judi/i,
        /description.*casino/i,
        /description.*poker/i,
        /description.*slot/i
      ];
      
      for (const pattern of gamblingMetaPatterns) {
        if (pattern.test(html)) {
          return true;
        }
      }
      
      // Method 4: Check for gambling-related scripts/libraries
      const gamblingScripts = [
        'gambling',
        'casino',
        'poker',
        'slot',
        'betting',
        'togel',
        'jackpot',
        'pragmatic',
        'habanero',
        'microgaming'
      ];
      
      for (const script of gamblingScripts) {
        if (content.includes(script)) {
          return true;
        }
      }
      
      return false;
      
    } catch (error) {
      console.error(`Error validating ${domain}:`, error);
      return false;
    }
  },

  isGamblingDomain(domain) {
    // Check if domain matches gambling patterns
    const gamblingPatterns = [
      /casino\./i,
      /poker\./i,
      /slot\./i,
      /bet\./i,
      /gambling\./i,
      /togel\./i,
      /judi\./i,
      /betting\./i,
      /lottery\./i,
      /bingo\./i,
      /\.casino$/i,
      /\.bet$/i,
      /\.gambling$/i,
      /\.poker$/i,
      /\.slot$/i,
      /\.vegas$/i,
      /\.jackpot$/i,
      /\.betting$/i,
      /\.lottery$/i,
      /\.bingo$/i
    ];
    
    return gamblingPatterns.some(pattern => pattern.test(domain));
  },

  generateBlocklist(validatedSites) {
    let blocklist = CONFIG.BLOCKLIST_HEADER;
    
    // Convert to AdGuard format
    for (const site of validatedSites) {
      blocklist += `||${site}^\n`;
    }
    
    // Add common gambling patterns as wildcards
    blocklist += `
! Common gambling patterns
||*.casino^
||*.bet^
||*.gambling^
||*.poker^
||*.slot^
||*.vegas^
||*.jackpot^
||*.betting^
||*.lottery^
||*.bingo^
`;
    
    return blocklist;
  }
};

// Helper function for manual testing
export function generateBlocklist(sites) {
  let blocklist = CONFIG.BLOCKLIST_HEADER;
  
  for (const site of sites) {
    blocklist += `||${site}^\n`;
  }
  
  return blocklist;
}