/**
 * Publisher Module
 * 
 * Generates blocklists in various formats:
 * - AdGuard Home
 * - hosts
 * - dnsmasq
 * - plain domain
 * - ABP
 * - RPZ (if possible)
 */

import type { Blocklist, BlocklistFormats } from '../types';

export interface PublisherConfig {
  header: string;
  footer: string;
  includeComments: boolean;
  includeStats: boolean;
}

export class Publisher {
  private config: PublisherConfig;

  constructor(config: Partial<PublisherConfig> = {}) {
    this.config = {
      header: config.header || '# Gambling Blocklist\n# Generated by Gambling Blocklist Generator\n# https://github.com/KancellKe2/gambling-blocklist\n',
      footer: config.footer || '\n# End of blocklist\n',
      includeComments: config.includeComments ?? true,
      includeStats: config.includeStats ?? true,
    };
  }

  generateFormats(blocklist: Blocklist): BlocklistFormats {
    return {
      adguard: this.generateAdGuard(blocklist),
      hosts: this.generateHosts(blocklist),
      dnsmasq: this.generateDnsmasq(blocklist),
      plainDomains: this.generatePlainDomains(blocklist),
      abp: this.generateABP(blocklist),
    };
  }

  private generateAdGuard(blocklist: Blocklist): string {
    const lines: string[] = [this.config.header];

    if (this.config.includeStats) {
      lines.push(`! Total domains: ${blocklist.domains.length}`);
      lines.push(`! Last updated: ${blocklist.lastUpdated.toISOString()}`);
      lines.push('');
    }

    for (const domain of blocklist.domains) {
      if (this.config.includeComments) {
        lines.push(`! ${domain.domain} - Confidence: ${domain.confidence.toFixed(2)} - Risk: ${domain.risk}`);
      }
      lines.push(`||${domain.domain}^`);
    }

    lines.push(this.config.footer);
    return lines.join('\n');
  }

  private generateHosts(blocklist: Blocklist): string {
    const lines: string[] = [this.config.header];

    if (this.config.includeStats) {
      lines.push(`# Total domains: ${blocklist.domains.length}`);
      lines.push(`# Last updated: ${blocklist.lastUpdated.toISOString()}`);
      lines.push('');
    }

    for (const domain of blocklist.domains) {
      if (this.config.includeComments) {
        lines.push(`# ${domain.domain} - Confidence: ${domain.confidence.toFixed(2)} - Risk: ${domain.risk}`);
      }
      lines.push(`0.0.0.0 ${domain.domain}`);
    }

    lines.push(this.config.footer);
    return lines.join('\n');
  }

  private generateDnsmasq(blocklist: Blocklist): string {
    const lines: string[] = [this.config.header];

    if (this.config.includeStats) {
      lines.push(`# Total domains: ${blocklist.domains.length}`);
      lines.push(`# Last updated: ${blocklist.lastUpdated.toISOString()}`);
      lines.push('');
    }

    for (const domain of blocklist.domains) {
      if (this.config.includeComments) {
        lines.push(`# ${domain.domain} - Confidence: ${domain.confidence.toFixed(2)} - Risk: ${domain.risk}`);
      }
      lines.push(`address=/${domain.domain}/0.0.0.0`);
    }

    lines.push(this.config.footer);
    return lines.join('\n');
  }

  private generatePlainDomains(blocklist: Blocklist): string {
    const lines: string[] = [this.config.header];

    if (this.config.includeStats) {
      lines.push(`# Total domains: ${blocklist.domains.length}`);
      lines.push(`# Last updated: ${blocklist.lastUpdated.toISOString()}`);
      lines.push('');
    }

    for (const domain of blocklist.domains) {
      lines.push(domain.domain);
    }

    lines.push(this.config.footer);
    return lines.join('\n');
  }

  private generateABP(blocklist: Blocklist): string {
    const lines: string[] = [this.config.header];

    if (this.config.includeStats) {
      lines.push(`! Total domains: ${blocklist.domains.length}`);
      lines.push(`! Last updated: ${blocklist.lastUpdated.toISOString()}`);
      lines.push('');
    }

    for (const domain of blocklist.domains) {
      if (this.config.includeComments) {
        lines.push(`! ${domain.domain} - Confidence: ${domain.confidence.toFixed(2)} - Risk: ${domain.risk}`);
      }
      lines.push(`||${domain.domain}^`);
    }

    lines.push(this.config.footer);
    return lines.join('\n');
  }

  generateRPZ(blocklist: Blocklist): string {
    const lines: string[] = [
      '$ORIGIN gambling-blocklist.',
      '$TTL 300',
      '@ IN SOA ns1.gambling-blocklist. admin.gambling-blocklist. (',
      '  2024010101 ; Serial',
      '  3600       ; Refresh',
      '  600        ; Retry',
      '  604800     ; Expire',
      '  300        ; Minimum TTL',
      ')',
      '@ IN NS ns1.gambling-blocklist.',
      '',
    ];

    for (const domain of blocklist.domains) {
      const rpzDomain = domain.domain.replace(/\./g, '.');
      lines.push(`${rpzDomain} CNAME .`);
    }

    return lines.join('\n');
  }

  getStatsSummary(blocklist: Blocklist): string {
    const stats = blocklist.stats;
    const lines: string[] = [
      `Total domains: ${stats.totalDomains}`,
      `High risk: ${stats.highRiskDomains}`,
      `Medium risk: ${stats.mediumRiskDomains}`,
      `Low risk: ${stats.lowRiskDomains}`,
      '',
      'Domains by category:',
    ];

    for (const [category, count] of Object.entries(stats.domainsByCategory)) {
      if (count > 0) {
        lines.push(`  ${category}: ${count}`);
      }
    }

    return lines.join('\n');
  }
}

export function createPublisher(config?: Partial<PublisherConfig>): Publisher {
  return new Publisher(config);
}